brain_two/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path("admin/", admin.site.urls),
    path("todos", include("todos.urls")),
]

todos/urls.py
from django.urls import path
from . import views

app_name = "todos"

urlpatterns = [
    path("", views.todo_list_list, name="todo_list_list"),
    path("<int:id>/", views.todo_list_detail, name="todo_list_detail"),
    path("<int:id>/edit/", views.todo_list_update, name="todo_list_update"),
    path("<int:id>/delete/", views.todo_list_delete, name="todo_list_delete"),
    path("create/", views.todo_list_create, name="todo_list_create"),
    path("items/create/", views.todo_item_create, name="todo_item_create"),
    path(
        "items/<int:id>/edit/", views.todo_item_update, name="todo_item_update"
    ),
]

todos/models.py
from django.db import models
from django.utils import timezone


# Create your models here.
class TodoList(models.Model):
    name = models.CharField(max_length=100)
    created_on = models.DateTimeField(default=timezone.now)


class TodoItem(models.Model):
    task = models.CharField(max_length=100)
    due_date = models.DateTimeField(null=True, blank=True)
    is_completed = models.BooleanField(default=False)
    list = models.ForeignKey(
        TodoList, related_name="items", on_delete=models.CASCADE
    )

todos/forms.py
from django import forms
from .models import TodoList


class TodoListForm(forms.ModelForm):
    class Meta:
        model = TodoList
        fields = ["name"]

todos/views.py
from django.shortcuts import render, redirect, get_object_or_404
from .models import TodoList, TodoItem
from .forms import TodoListForm, TodoItemForm


# Create your views here.
def todo_list_list(request):
    todo_lists = TodoList.objects.all()
    context = {
        "todo_lists": todo_lists,
    }
    return render(request, "todos/todo_list_list.html", context)


def todo_list_detail(request, id):
    todo_list = get_object_or_404(TodoList, id=id)
    context = {
        "todo_list": todo_list,
    }
    return render(request, "todos/todo_list_detail.html", context)


def todo_list_create(request):
    if request.method == "POST":
        form = TodoListForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect("todos:todo_list_list")
    else:
        form = TodoListForm()
    return render(request, "todos/todo_list_create.html", {"form": form})


def todo_list_update(request, id):
    todo_list = get_object_or_404(TodoList, id=id)
    if request.method == "POST":
        form = TodoListForm(request.POST, instance=todo_list)
        if form.is_valid():
            form.save()
            return redirect("todos:todo_list_detail", id=id)
    else:
        form = TodoListForm(instance=todo_list)
    return render(request, "todos/todo_list_update.html", {"form": form})


def todo_list_delete(request, id):
    todo_list = get_object_or_404(TodoList, id=id)
    if request.method == "POST":
        todo_list.delete()
        return redirect("todos:todo_list_list")
    return render(
        request, "todos/todo_list_delete.html", {"todo_list": todo_list}
    )


def todo_item_create(request):
    if request.method == "POST":
        form = TodoItemForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect("todos:todo_list_list")
    else:
        form = TodoItemForm()
    return render(request, "todos/todo_item_create.html", {"form": form})


def todo_item_update(request, id):
    todo_item = get_object_or_404(TodoItem, id=id)
    if request.method == "POST":
        form = TodoItemForm(request.POST, instance=todo_item)
        if form.is_valid():
            form.save()
            return redirect("todos:todo_list_detail", id=todo_item.list.id)
    else:
        form = TodoItemForm(instance=todo_item)
    return render(request, "todos/todo_item_update.html", {"form": form})

todos/templates/todos/detail.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Todo Lists</title>
</head>
<body>
    <main>
        <div>
            <a href="{% url 'todos:todo_list_delete' todo_list.id %}">Delete this list</a>
            <a href="{% url 'todos:todo_item_create' %}">Create New Todo Item</a>
            <a href="{% url 'todos:todo_list_create' %}">Create New Todo List</a>
            <a href="{% url 'todos:todo_list_update' todo_list.id %}">Edit this list</a>
        </div>
        <h1>{{My Lists}}</h1>
        <h2>Tasks</h2>
        <p><a href="{% url 'todos:todo_item_create' %}">Create a new item</a></p>
        <table>
            <thead>
                <tr>
                    <th>Task</th>
                    <th>Due date</th>
                </tr>
            </thead>
            <tbody>
                {% for item in todo_item.items.all %}
                <tr>
                    <td>{{ item.task }}</td>
                    <td>{{ item.due_date }}</td>
                </tr>
                {% endfor %}
            </tbody>
        </table>
    </main>

</body>
</html>

todos/templates/todos/todo_item_create.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Create Todo Item</title>
</head>
<body>
    <main>
        <div>
            <h1>Create a new item</h1>
            <form method="post">
                {% csrf_token %}
                <label for="task">Task:</label>
                <input type="text" name="task"><br>

                <label for="due_date">Due Date:</label>
                <input type="text" name="due_date"><br>

                <label for="is_completed">Is Completed:</label>
                <input type="checkbox" name="is_completed"><br>

                <label for="list">List:</label>
                <select name="list">
                    {% for todo_list in todo_lists %}
                        <option value="{{ todo_list.id }}">{{ todo_list.name }}</option>
                    {% endfor %}
                </select><br>

                <button type="submit">Create</button>
            </form>
        </div>

    </main>

</body>
</html>

todos/templates/todos/todo_item_update.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Edit Todo Item</title>
</head>
<body>
    <main>
        <div>
            <h1>Update item</h1>
            <form method="post">
                {% csrf_token %}
                <label for="task">Task:</label>
                <input type="text" name="task" value="{{ form.task.value }}"><br>

                <label for="due_date">Due Date:</label>
                <input type="text" name="due_date" value="{{ form.due_date.value }}"><br>

                <label for="is_completed">Is Completed:</label>
                <input type="checkbox" name="is_completed" {% if form.is_completed.value %}checked{% endif %}><br>

                <label for="list">List:</label>
                <select name="list">
                    {% for todo_list in todo_lists %}
                        <option value="{{ todo_list.id }}" {% if todo_list.id == form.list.value %}selected{% endif %}>{{ todo_list.name }}</option>
                    {% endfor %}
                </select><br>

                <button type="submit">Update</button>
            </form>
        </div>

    </main>

</body>
</html>

todos/templates/todos/todo_list_create.html
<!DOCTYPE html>
<html lang="en">
<head>
    <title>Create Todo List</title>
</head>
<body>
    <main>
        <div>
            <h1>Create a new list</h1>
            <form method="post">
                {% csrf_token %}
                {{ form.as_p }}
                <button type="submit">Create</button>
            </form>
        </div>
    </main>
</body>
</html>

todos/templates/todos/todo_list_delete.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Delete Todo List</title>
</head>
<body>
    <main>
        <div>
            <h1>Delete Todo List</h1>
            <p>Are you sure you want to delete "{{ todo_list.name }}"?</p>
            <form method="post">
                {% csrf_token %}
                <button type="submit">Delete</button>
            </form>
        </div>

    </main>

</body>
</html>

todos/templates/todos/todo_list_list.html
<!DOCTYPE html>
<html lang="en">
<head>
    <title>Todo Lists</title>
</head>
<body>
    <main>
        <div>
            <a href="{% url 'todos:todo_list_create' %}">Create New Todo List</a>
        </div>
            <h1>My Lists</h1>
            <p><a href="{% url 'todos:todo_list_create' %}">Create a new list</a></p>
            <table>
                <thead>
                    <tr>
                        <th>Name</th>
                        <th>Number of items</th>
                    </tr>
                </thead>
                <tbody>
                    {% for todo_list in todo_lists %}
                        <tr>
                            <td><a href="{% url 'todos:todo_list_detail' todo_list.id %}">{{ todo_list.name }}</a></td>
                            <td>{{ todo_list.items.count }}</td>
                        </tr>
                    {% endfor %}
                </tbody>
            </table>

    </main>
</body>
</html>

todos/templates/todos/todo_list_update.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Edit Todo List</title>
</head>
<body>
    <main>
        <div>
            <h1> Update list</h1>
            <form method="post">
                {% csrf_token %}
                {{ form.as_p }}
                <button type="submit">Update</button>
            </form>
        </div>
    </main>
</body>
</html>